### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-21_yp3vv/staticmodel/staticmodel/VERSION.txt'

### ISSUE THREAD

**Issue by emilt27** [wsmith323/staticmodel#2]
Hello! 
I'm getting this error latest few hours during installation. It seems it's related to latest updates.

**Comment by emilt27** [comment]
It works with **staticmodel==0.2.0**

**Comment by wsmith323** [comment]
Fixed in version 0.3.3.
